version: "3"

services:
  overviewer:
    image: ghcr.io/zottelchen/overviewer:latest
    # or
    # image: zottelchen/overviewer:latest
    command: /app/world /app/out #edit this line to your needs, see docs at https://docs.overviewer.org/en/latest/running/
    volumes:
      #- './render.conf:/app/render.conf'
      - "./world:/app/world"
      - "./out:/app/out"
