services:
  proxyraye:
    image: ghcr.io/zottelchen/proxyraye:latest
    # or
    # image: zottelchen/proxyraye:latest
    restart: unless-stopped
    ports:
      - "8069:3000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/status || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
    - ENABLE_REDIS=true
    - REDIS_URL=redis://redis:6379

  redis:
      image: cgr.dev/chainguard/redis:latest
      container_name: redis
      restart: unless-stopped