name: Calckey - Build & Push

on:
  push:
    branches:
      - "main"
    paths:
      - "calckey/Dockerfile"
      - ".github/workflows/calckey.yml"

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */6 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Hadolint:
    name: 🧪Run hadolint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: 🎯 Checkout code
        uses: actions/checkout@v3

      - name: 🐎Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./calckey/Dockerfile
          format: sarif
          ignore: DL3008,DL3007
          output-file: hadolint-results.sarif
          no-fail: true

      - name: ⚡Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true

  Build-and-Push:
    name: 🐋Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: 👷‍♀️ Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: 👷‍♂️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🐋Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 👷‍♂️🐋👷‍♀️ Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:calckey"
          platforms: linux/amd64,linux/arm64/v8
          labels: |
            org.opencontainers.image.source=https://github.com/Zottelchen/docker-container
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=Calckey is an open source, decentralized social media platform that's free forever!
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            zottelchen/calckey:latest
          #  ghcr.io/zottelchen/calckey:latest
          # quay.io/<>/calckey:latest

  Update-Readme-on-Dockerhub:
    name: 📖 Update repo description on DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: 🎯 Checkout code
        uses: actions/checkout@v3

      - name: 📖 Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: zottelchen/calckey
          readme-filepath: ./calckey/README.md
