name: Enhanced Twitch Drop Bot - Docker🐋

on:
  push:
    branches:
      - "main"
    paths:
      - "enhanced-ttvdropbot/Dockerfile"
      - ".github/workflows/enhanced-ttvdropbot_docker.yml"

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */6 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Build-and-Push:
    name: 🐋Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: 👷‍♀️ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 👷‍♂️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🐙 Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐋Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 👷‍♂️🐋👷‍♀️ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:enhanced-ttvdropbot"
          platforms: linux/amd64,linux/arm64/v8
          labels: |
            org.opencontainers.image.source=https://github.com/Zottelchen/docker-container
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=Minecraft Enhanced Twitch Drop Bot renders Minecraft maps into a set of images which can be combined into a Google Maps like interface on a web page.
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            zottelchen/enhanced-ttvdropbot:latest
            ghcr.io/zottelchen/enhanced-ttvdropbot:latest
          # quay.io/<>/enhanced-ttvdropbot:latest
