name: wmill CLI - Description📖

on:
  push:
    branches:
      - "main"
    paths:
      - "wmill-cli/README.md"
      - "wmill-cli/docker-compose.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Update-Readme-on-Dockerhub:
    name: 📖 Update repo description on DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: 🎯 Checkout code
        uses: actions/checkout@v4

      - name: ↪ Replace placeholders in README
        run: |
          awk -v yaml="$(cat ./wmill-cli/docker-compose.yaml)" '{
            if ($0 == "[Here](https://github.com/Zottelchen/docker-container/tree/main/wmill-cli/docker-compose.yaml)") {
                print "```yaml"
                print yaml
                print "```"
            } else {
                print $0
            }
          }' ./wmill-cli/README.md > ./wmill-cli/README.tmp.md
          mv ./wmill-cli/README.tmp.md ./wmill-cli/README.md

      - name: 📖 Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: zottelchen/wmill-cli
          readme-filepath: ./wmill-cli/README.md
